In [3]:
import yaml
import numpy as np

In [4]:
data = yaml.safe_load(open('OD.yaml'))
data['Simulation']['NumberOfPhotons'] = np.array([1200, 800, 4]) 

# with open('OD.yaml', 'w') as f:
#     yaml.safe_dump(data, f, default_flow_style=False)

In [5]:
# data = yaml.safe_load(open('OD.yaml'))
data['Simulation']['NumberOfPhotons']


array([1200,  800,    4])

In [6]:
NumPerMuon = np.array([2,3,4])

a2 = np.ones((3))*2
a3 = np.ones((3))*3
a4 = np.ones((3))*4

# Array = np.array([a2,a2,a3,a3,a3,a4,a4,a4,a4,])

Array = np.array([2,2,3,3,3,4,4,4,4,])

print(Array, Array.shape)

#larger number of photons will be the dimension of one size
maxlength = np.max(NumPerMuon)

thirdDim = 0

if thirdDim > 0: # extra work if there is another dimension to the data
    #make empty array to fill with proper shape
    newshape = np.zeros( (len(NumPerMuon), maxlength, thirdDim))

    for i,num in enumerate(NumPerMuon):
        if i==0: #base case
            newshape[i] = np.append(Array[:num], np.zeros((maxlength-num, thirdDim)), axis=0)

        else:
            newshape[i] = np.append(Array[np.sum(NumPerMuon[:i]):np.sum(NumPerMuon[:i+1])], np.zeros((maxlength-num, thirdDim)), axis=0)

elif thirdDim == 0:
    #make empty array to fill with proper shape
    newshape = np.zeros( (len(NumPerMuon), maxlength))
    
    for i,num in enumerate(NumPerMuon):
        if i==0: #base case
            newshape[i] = np.pad(Array[:num], (0, maxlength-num))
        else:
            newshape[i] = np.pad(Array[np.sum(NumPerMuon[:i]):np.sum(NumPerMuon[:i+1])], (0, maxlength-num) )


newshape
# unshape.resize((len(a), max(a)))
# unshape

[2 2 3 3 3 4 4 4 4] (9,)


array([[2., 2., 0., 0.],
       [3., 3., 3., 0.],
       [4., 4., 4., 4.]])

In [14]:
A = np.linspace(0,1)
B = None

In [17]:
def check(x):
    if x is None:
        print('none')
    else:
        print('something')

In [20]:
check(A)

something
